<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from /Users/jitendra/src/civicrm/tools/extensions/nz.co.fuzion.transactional/xml/schema/CRM/Transactional/RecipientReceipt.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:216a8d7d7e0dc87ab3d9a275f29f45bd)
 */

/**
 * Database access object for the RecipientReceipt entity.
 */
class CRM_Transactional_DAO_RecipientReceipt extends CRM_Core_DAO {

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_recipient_receipt';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique RecipientReceipt ID
   *
   * @var int
   */
  public $id;

  /**
   * Event Queue id
   *
   * @var int
   */
  public $queue_id;

  /**
   * Activity id of the receipt
   *
   * @var int
   */
  public $receipt_activity_id;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_recipient_receipt';
    parent::__construct();
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => ts('Unique RecipientReceipt ID'),
          'required' => TRUE,
          'where' => 'civicrm_recipient_receipt.id',
          'table_name' => 'civicrm_recipient_receipt',
          'entity' => 'RecipientReceipt',
          'bao' => 'CRM_Transactional_DAO_RecipientReceipt',
          'localizable' => 0,
        ],
        'queue_id' => [
          'name' => 'queue_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => ts('Event Queue id'),
          'where' => 'civicrm_recipient_receipt.queue_id',
          'table_name' => 'civicrm_recipient_receipt',
          'entity' => 'RecipientReceipt',
          'bao' => 'CRM_Transactional_DAO_RecipientReceipt',
          'localizable' => 0,
        ],
        'receipt_activity_id' => [
          'name' => 'receipt_activity_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => ts('Activity id of the receipt'),
          'where' => 'civicrm_recipient_receipt.receipt_activity_id',
          'table_name' => 'civicrm_recipient_receipt',
          'entity' => 'RecipientReceipt',
          'bao' => 'CRM_Transactional_DAO_RecipientReceipt',
          'localizable' => 0,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'recipient_receipt', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'recipient_receipt', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
